In [1]:
import pandas as pd
import numpy as np
import urllib
import pyodbc
import pandas as pd
import sqlalchemy as sa
import numpy as np
import math

connection_string = (
    'Driver={ODBC Driver 17 for SQL Server};'
    'SERVER=118.69.201.34;'
    'Database=FLC_SHOP_SALES_DATAWAREHOUSE;'
    'UID=ecom_user;'
    'PWD=Ec0m@12345;'
    'Trusted_Connection=no;'
)

connection_uri = f"mssql+pyodbc:///?odbc_connect={urllib.parse.quote_plus(str(connection_string))}"
engine = sa.create_engine(connection_uri, fast_executemany=True)

In [2]:
df1 = pd.read_excel(r'D:\CALL_CALO.xlsx',dtype=object)

In [4]:
df1 = df1.drop(df1.columns[[0,1]], axis=1)

In [5]:
df1

,PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY_NAME,PRODUCT_GROUP_NAME,SHOP_CODE,SHOP_NAME,REGION_NAME_5,CUSTOMER_PHONE,MAX_INVOICE,MAX_DATE,_DIFF,LIST_AMOUNT_AF_VAT,ITEM_QTY,UNIT,Phone,SEGMENT
0,16320,ÁO MƯA - HÀNG TẶNG,KHÁC,Unspecified,80322,LC AGG 67 Trần Phú,An Giang,84F0EB236DDCCE6E585C50B6A3F86FC8,68840325,2022-07-20,217,0,1,Cái,0587967197,calo
1,29135,SAVI PLUS MULTIVITAMIN T/20,TPCN,THUỐC BỔ,80047,LC HCM 159-161 Nguyễn Bình,Hồ Chí Minh - KV9,3A421F24FABB27BC7F8E9EAA4B955D7C,48679067,2022-03-04,355,18000,1,Tuýp,0908792483,calo
2,1978,CLOZAPYL 100MG TORRENT 10X10,THUỐC,THUỐC THẦN KINH,80083,LC HPG 313 Hai Bà Trưng,Hải Phòng,B32DC9FE633EE62ECF5A7A0B3EB970A0,63943463,2022-06-18,249,165300,3,Vỉ,0775353838,calo
3,30293,NQV-DAILY SG,TPCN,Unspecified,80347,"LC HNI Tổ 10, 126 Vĩnh Hưng",Hà Nội - KV5,EAD065B8EE3E0E169F1D227C3B10B824,71781802,2022-08-07,199,2300000,2,Hộp,0979517178,calo
4,15952,PHÍ GIAO HÀNG,KHÁC,MỞ TỦ,80227,"LC NAN 1-2-3-4 Chợ Ga, Phan Bội Châu",Nghệ An,D80FDEB8A7AAAE58D713FBB91239824D,73466036,2022-08-16,190,25000,25,DVT,0943756386,calo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126573,23436,HOYA V-IDOL BLUECUT 1.56 CẬN-0.50,MẮT KÍNH,TRÒNG KÍNH,80303,LC HCM 379-381 Hai Bà Trưng,Hồ Chí Minh - KV4,417D2D360587F9C45FFEDDD418CEC84C,53215612,2022-03-31,328,144000,1,Chiếc,0937781703,calo
126574,26209,HOYA 160 BLUECONTROL STELLIFY VIỄN+250,MẮT KÍNH,TRÒNG KÍNH,80006,LC HCM 72 Tân Mỹ,Hồ Chí Minh - KV7,7CD6363752823703B3021B246DF35984,39481568,2021-12-18,431,732000,2,Chiếc,0909219012,calo
126575,23960,HOYA V-IDOL HMC 1.56 VIỄN+1.50,MẮT KÍNH,TRÒNG KÍNH,80303,LC HCM 379-381 Hai Bà Trưng,Hồ Chí Minh - KV4,90993EBDD739E29211D726583B5C0E3E,50492076,2022-03-15,344,168000,2,Chiếc,0903815572,calo
126576,23964,HOYA V-IDOL HMC 1.56 VIỄN+2.50,MẮT KÍNH,TRÒNG KÍNH,80303,LC HCM 379-381 Hai Bà Trưng,Hồ Chí Minh - KV4,89923DE2C319EEEC0FD0C3B59C014E2E,41366908,2022-01-06,412,168000,2,Chiếc,0906661122,calo
126577,23714,HOYA V-IDOL HC 1.56 VIỄN+2.25,MẮT KÍNH,TRÒNG KÍNH,80014,LC HCM 106-108 Tô Ngọc Vân,Hồ Chí Minh - KV19,683E0A83B66FB19FD6355955780ED52D,67554310,2022-07-13,224,108000,2,Chiếc,0903031199,calo

In [12]:
df2

,PRODUCT_KEY,PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY_NAME,PRODUCT_GROUP_NAME
0,250853,345526,NƯỚC SINH HOẠT,TÀI SẢN,CHI PHÍ HOẠT ĐỘNG
1,161810,345528,PHỤ GIA NẤU HÀNG NGÀY,TÀI SẢN,CHI PHÍ HOẠT ĐỘNG
2,166509,345529,TIỀN ĐI CHỢ HÀNG NGÀY,TÀI SẢN,CHI PHÍ HOẠT ĐỘNG
3,268961,345531,TIỀN RÁC,TÀI SẢN,CHI PHÍ HOẠT ĐỘNG
4,602089,345532,NƯỚC UỐNG,TÀI SẢN,CHI PHÍ HOẠT ĐỘNG
...,...,...,...,...,...
32574,427223,24479,HOYA V-IDOL BIFOCAL+125/275L,MẮT KÍNH,TRÒNG KÍNH
32575,515663,26099,HOYA 160 BLUECONTROL STELLIFY LOẠN-300-075,MẮT KÍNH,TRÒNG KÍNH
32576,724455,24362,HOYA V-IDOL SUNPLUS 1.56 LOẠN -5.00-1.75,MẮT KÍNH,TRÒNG KÍNH
32577,145350,24771,HOYA V-IDOL HMC 1.60 LOẠN-3.00-0.25,MẮT KÍNH,TRÒNG KÍNH
32578,728685,26612,HOYA 160-STELIFY-LOẠN-425-075,MẮT KÍNH,TRÒNG KÍNH

In [11]:
# b = df2.groupby(['CUSTOMER_PHONE','SHOP_CODE','SHOP_NAME','REGION_NAME_5','INVOICE_HEADER','MAX_DATE','_DIFF'], as_index = False).agg(PRODUCT_CODE = ('PRODUCT_CODE',"unique"), PRODUCT_NAME = ('PRODUCT_NAME',"unique"), LIST_AMOUNT_AF_VAT = ('LIST_AMOUNT_AF_VAT',"unique"))

In [6]:
b = df1.groupby(['Phone','SEGMENT','CUSTOMER_PHONE','SHOP_CODE','SHOP_NAME','REGION_NAME_5','MAX_INVOICE','MAX_DATE','_DIFF'], as_index = False).agg(PRODUCT_CODE = ('PRODUCT_CODE',"unique"), PRODUCT_NAME = ('PRODUCT_NAME',"unique"), PRODUCT_CATEGORY_NAME = ('PRODUCT_CATEGORY_NAME',"unique"), PRODUCT_GROUP_NAME = ('PRODUCT_GROUP_NAME',"unique"), ITEM_QTY = ('ITEM_QTY',"unique"), UNIT = ('UNIT',"unique"))

In [16]:
df1.rename(columns={ df1.columns[0]: 'CUSTOMER_PHONE'}, inplace = True)

In [7]:
df2.rename(columns={ df2.columns[0]: 'CUSTOMER_PHONE', df2.columns[1]: 'MAX_INVOICE', df2.columns[2]: 'MAX_DATE', df2.columns[3]: '_DIFF', df2.columns[4]: 'SHOP_KEY', df2.columns[5]: 'PRODUCT_KEY', df2.columns[6]: 'LIST_AMOUNT_AF_VAT', df2.columns[7]: 'ITEM_QTY', df2.columns[8]: 'UNIT'}, inplace = True)

In [7]:
df2.rename(columns={ df2.columns[0]: 'CUSTOMER_KEY', df2.columns[1]: 'CUSTOMER_CODE', df2.columns[2]: 'CUSTOMER_NAME', df2.columns[3]: 'CUSTOMER_PHONE'}, inplace = True)

In [2]:
df1 = pd.read_csv(r'E:\segment1.csv', header = None)

In [3]:
df1

                                        0
0        7EB86865F78C604C20E4C51B08655A3C
1        1A410F200E18111DF9AB6275FE6F182B
2        042C7B2BDED8055A895DDF008F2DC63D
3        2B59AF71B5762B928B8F1B3F094FB1E9
4        834F1C31B75E878FD0D58C514C5CEE7F
...                                   ...
4609547  088CBF11A628F2158670F44567296C30
4609548  8BA92E3622A03EE0FC90C6CE5ADC50F1
4609549  2D1C8A13134B08F72DB84A151FA24F11
4609550  410F4D35F472C0B2A5FC79CA4440C0B3
4609551  46BE837C8D1F5F6C7ABF316D106F50B1

[4609552 rows x 1 columns]

In [4]:
df3 = pd.read_csv(r'E:\mantinh1.csv', header = None)

In [5]:
df3

                                        0
0        C31739CD3B3C0CAD1F0C2F5982AF39BB
1        28ADABD2BC6E2DEADE67D3D737565D2A
2        A4531D9CE53D7D70782F0818BC887EF4
3        0E02D79706268502B8174AEFA015CB27
4        0A4CE8AF73B625F6B46561783AC2B77E
...                                   ...
4450462  D55C4BD53C4F3FE318AA13BB96922F83
4450463  4DD870E06556E5738986017A06DF63C2
4450464  F5F8B16330BCBE07EAD536C2945E454A
4450465  196B272ED5FCA6178CDE2B91F1C2BD0B
4450466  7CBFBABC774E2DA83AC1DE0DA63E325D

[4450467 rows x 1 columns]

In [21]:
Merge = df3.merge(df1, how='inner', on='CUSTOMER_PHONE')

In [22]:
Merge

                           CUSTOMER_PHONE
0        4E08142B36AF7F15D29CB1F6C7B0ABC1
1        94B719357E3C003FBFC2C3B213557C48
2        3A3B34B9CD356CB1C41BAFDAEA0CDE10
3        AEA3D341DAFE478D81CE946B895F2031
4        B5E6359487117814C7DFE087F67252EB
...                                   ...
1417027  2ADA2108F9A7466A9148F0FCDADDC251
1417028  92E784AB91B1FDD344D3E603F96C19EA
1417029  3A202F593CCF9CF4E4E0F7EE9C4F203A
1417030  4DD870E06556E5738986017A06DF63C2
1417031  7CBFBABC774E2DA83AC1DE0DA63E325D

[1417032 rows x 1 columns]

In [23]:
Merge.to_csv(r'E:\roibomantinh.csv')

In [7]:
b

,Phone,SEGMENT,CUSTOMER_PHONE,SHOP_CODE,SHOP_NAME,REGION_NAME_5,MAX_INVOICE,MAX_DATE,_DIFF,PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY_NAME,PRODUCT_GROUP_NAME,ITEM_QTY,UNIT
0,02033829452,calo,FAC90C282EC1061404D192FFB7564FC3,80210,LC QNH 15-17 Phố Hoàng Long,Quảng Ninh,69678278,2022-07-25,212,"[500234, 6512, 29255]","[HOẠT HUYẾT TRƯỜNG PHÚC 3X10, SÂM NHUNG BỔ THẬ...","[THUỐC, TPCN]","[THUỐC TĂNG CƯỜNG TUẦN HOÀN NÃO, THUỐC TRỊ BỆN...","[2, 1]",[Hộp]
1,02083756410,calo,746AF32461B2C4C2421991874F04E36B,80427,LC TNN 199 Bến Oánh,Thái Nguyên,63988845,2022-06-19,248,"[14926, 14999, 30662]","[HUMAN ALBUMIN 200G/L 20% BAXTER 50ML, NATRI C...","[THUỐC, TRANG THIẾT BỊ Y TẾ]","[DỊCH TRUYỀN, DỤNG CỤ Y TẾ]",[1],"[Hộp, Chai, Bộ]"
2,02223824430,calo,D27DFACBFFAB7683134627D907DED6B8,80108,LC BNH 57 Trần Hưng Đạo,Bắc Ninh,66756509,2022-07-07,230,[33792],[VIÊN HỖ TRỢ TĂNG CƯỜNG SINH LỰC CHO NAM FIRST...,[TPCN],[SINH LÝ],[1],[Hộp]
3,02253700610,calo,0B2D4E9215995D7D5949D8EB19670D51,80116,LC HPG 70 Nguyễn Đức Cảnh,Hải Phòng,61560128,2022-06-02,265,"[20662, 21676]","[VITATREE GINKGO PLUS 6000 Q10 60V KINGPHAR, P...",[TPCN],"[THẦN KINH NÃO, XƯƠNG KHỚP]",[1],[Hộp]
4,02253731434,calo,EB771FB5A6C4F0AA983A7BE7659B5E3F,80143,LC HPG 72 Cát Bi,Hải Phòng,44645644,2022-02-06,381,"[17253, 345423]","[KHẨU TRANG THIÊN THỦY 4 LỚP, LUTEIN NATURES B...","[TRANG THIẾT BỊ Y TẾ, TPCN]","[ĐỒ BẢO HỘ, MẮT]","[5, 1]","[Cái, Hộp]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48753,0996748121,calo,F9987AA6323050CF8A84A7C4F55EC582,80007,LC HCM 422-424 CMT8,Hồ Chí Minh - KV15,24478360,2021-05-08,655,"[2814, 15275, 29312, 5714, 2303]","[ENTEROGERMINA 2 TỶ/ ỐNG 5ML SANOFI 2X10, AGOS...",[THUỐC],"[THUỐC TIÊU HÓA, THUỐC XƯƠNG KHỚP, THUỐC SÁT K...","[1, 2]","[Vỉ, Hộp, Chai]"
48754,0996993123,calo,FA2173042236132ACABF76C6F9A69211,80202,LC HCM 198O Xóm Chiếu,Hồ Chí Minh - KV7,29473846,2021-07-26,576,"[15942, 2954, 4453, 20697]","[SÚC MIỆNG HỌNG MEDORAL MERAP 250ML, EXFORGE 5...",[THUỐC],"[DUNG DỊCH SÚC MIỆNG, THUỐC TIM MẠCH HUYẾT ÁP,...","[1, 10]","[Hộp, Viên, Vỉ]"
48755,0997003868,calo,08AA1121D0D98B7BD7A1C15057539463,80006,LC HCM 72 Tân Mỹ,Hồ Chí Minh - KV7,28094516,2021-07-07,595,"[2944, 21370, 1954]","[EUVIOXCIN HÀ TÂY 2X10, TELFAST KIDS 30MG SANO...",[THUỐC],"[THUỐC KHÁNG SINH, THUỐC CHỐNG DỊ ỨNG]","[17, 10]",[Viên]
48756,0997193968,calo,15EDD0E34E11D1A7DA228098FFC7D801,80016,LC HCM 404 Nguyễn Oanh,Hồ Chí Minh-KV12,25535355,2021-05-27,636,"[5357, 620, 2009]","[NOOTROPIL 800MG GSK 3X15, ALLOPURINOL 300MG S...",[THUỐC],"[THUỐC TĂNG CƯỜNG TUẦN HOÀN NÃO, THUỐC TRỊ GOUT]",[1],"[Vỉ, Hộp]"
48757,0997771779,calo,6F8D1B8294DA758E4463D731EB9D02E5,80035,LC LAN 173 Hùng Vương,Long An,36765390,2021-11-17,462,[2814],[ENTEROGERMINA 2 TỶ/ ỐNG 5ML SANOFI 2X10],[THUỐC],[THUỐC TIÊU HÓA],[1],[Hộp]

In [8]:
b.to_excel(r'D:\CALL_CALO_1.xlsx')